name: Run Cypress Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: npm install
      
    - name: Run Cypress tests
      run: npm run test:cypress
