name: trigger jenkins job
on: 
  workflow_dispatch: {}
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "http://jenkins-public-lb-1226399302.eu-west-1.elb.amazonaws.com:8080/"
        user: "ali"
        token: ${{ secrets.JENKINS_APIKEY }}
        job: "RabbiesGitHubActionsDemo"
